### ISSUE TITLE
Python 3.10 Lambda image throws Segmentation Violation when running locally

### ISSUE THREAD

**Issue by eric-musliner** [aws/aws-lambda-base-images#100]
Any lambda image release for 3.10 past `public.ecr.aws/lambda/python:3.10.2023.05.07.17` cause the following error on receipt of a post request to the test endpoint when running locally

```
23 May 2023 23:13:20,652 [DEBUG] (rapid) invoke: -> POST /2015-03-31/functions/function/invocations map[Accept:[*/*] Accept-Encoding:[gzip, deflate] Baggage:[sentry-trace_id=7155adfe5fd24e6da8dfb672ecbf4975,sentry-environment=dev,sentry-release=avalon%40UNSET,sentry-transaction=/api/graph/%7Bgraphid%7D/enrichment-results/%7Btransaction_id%7D] Connection:[keep-alive] Content-Length:[34] Content-Type:[application/json] Sentry-Trace:[7155adfe5fd24e6da8dfb672ecbf4975-9b87b2295bde058b-0] User-Agent:[python-requests/2.28.2]]
23 May 2023 23:13:20,652 [INFO] (rapid) ReserveFailed: AlreadyReserved
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x68c30f]

goroutine 68 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
/LambdaRuntimeLocal/lambda/rapidcore/server.go:653 +0xef
created by go.amzn.com/lambda/rapidcore.(*Server).Invoke
/LambdaRuntimeLocal/lambda/rapidcore/server.go:636 +0x23d
```

**Comment by shaicoleman** [comment]
Same issue with `public.ecr.aws/lambda/ruby:3.2.2023.12.05.17-x86_64`, image id: `d95983042957`

```
START RequestId: f998bff1-47d4-4206-a8f6-7696b92be10f Version: $LATEST
08 Dec 2023 10:57:13,427 [INFO] (rapid) ReserveFailed: AlreadyReserved
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6af115]

goroutine 53 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
	/LambdaRuntimeLocal/lambda/rapidcore/server.go:666 +0xf5
created by go.amzn.com/lambda/rapidcore.(*Server).Invoke
	/LambdaRuntimeLocal/lambda/rapidcore/server.go:649 +0x23d
```

I think this happens when there is more than one lambda executing at the same time

**Comment by achernyakov-rvbd** [comment]
EDIT: In case someone else stumbles upon this, I was able to work around the issue by passing the "-d" option to "sam local" which puts sam in debug mode, which in turns disables multi-threading, preventing the crash.  Seems hard to believe that such a bug has been in this for so long.

Anyone know of a resolution?  I'm hitting the exact same error using SAM CLI, version 1.105.0.

```
START RequestId: 865a1b4f-7c4e-466f-acb2-c7f06cc0cd6e Version: $LATEST
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6af115]

goroutine 15 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
	/LambdaRuntimeLocal/lambda/rapidcore/server.go:666 +0xf5
created by go.amzn.com/lambda/rapidcore.(*Server).Invoke
	/LambdaRuntimeLocal/lambda/rapidcore/server.go:649 +0x23d
No response from invoke container for HelloWorldFunction                                                                                                           
```

I too only see this when invoking more than one execution at the same time.

**Comment by jmehnle** [comment]
Still happening with the Python 3.12 image.

**Comment by diego12o** [comment]
I had the same issue with version 1.105.0 and using Python 3.12. I updated to the latest version of SAM (1.119.0) and it was resolved. It was not necessary to enable debug mode.

**Comment by maxday** [comment]
Thanks for raising this, we will have a look at this panic in the RIE

**Comment by cooperaj** [comment]
> Thanks for raising this, we will have a look at this panic in the RIE

If it helps any I've just started seeing this today after switching from the 3 year old RIE we had in the repo to the newest one provided in the al2023 amazon image. Since we need functional debugging I'm going to roll back to that previous working version.
