### ISSUE TITLE
Nodejs18 aws-sdk createPresignedPost not working

### ISSUE THREAD

**Issue by ivanmartos** [aws/aws-lambda-base-images#115]
Currenlty nodejs18 runtime is using aws-sdk version  `3.188.0` (based on https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html)

With this SDK version bundled in layer `createPresignedPost` does not work and it returns error 
```
error occurred EndpointError: A region must be set when sending requests to S3.
    at evaluateErrorRule (/opt/nodejs/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateErrorRule.js:13:11)
    at evaluateRules (/opt/nodejs/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateRules.js:17:55)
    at resolveEndpoint (/opt/nodejs/node_modules/@aws-sdk/util-endpoints/dist-cjs/resolveEndpoint.js:28:48)
    at Object.defaultEndpointResolver [as endpointProvider] (/opt/nodejs/node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js:7:49)
    at getEndpointFromInstructions (/var/runtime/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:10:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createPresignedPost (/var/runtime/node_modules/@aws-sdk/s3-presigned-post/dist-cjs/createPresignedPost.js:46:60)
```

Code
```
import {S3Client } from '@aws-sdk/client-s3'
const client = new S3Client()
import {
  createPresignedPost as createPresignedPostLib,
  PresignedPost,
  PresignedPostOptions,
} from '@aws-sdk/s3-presigned-post'

export const createPresignedPost = async (params: PresignedPostOptions): Promise<PresignedPost> => {
  return createPresignedPostLib(client, params)
}
```

Lambda is deployed in `eu-west-1` region

Once I deployed lambda with bundled runtime dependencies
```
"@aws-sdk/client-s3": "^3.414.0",
"@aws-sdk/s3-presigned-post": "^3.414.0",
```
issue was fixed

Please update lambda layer aws-sdk version

**Comment by anzheyazzz** [comment]
This has been updated. Closing issue.
