### ISSUE TITLE
Error: Cannot find module 'index'

### ISSUE THREAD

**Issue by SinBirb** [aws/aws-lambda-base-images#122]
Hi, does any of the nodejs images have version 3.0 of the [AWS Lambda NodeJS Runtime Interface Client](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client) installed, which supports ESModules?

I'm getting a Runtime.ImportModuleError using the Images in a local docker container with my Dockerfile, using `public.ecr.aws/lambda/nodejs:20-preview` as well as `public.ecr.aws/lambda/nodejs:18`.

Or do you have another idea why I get this error when sending a simple test request to `http://localhost:9000/2015-03-31/functions/function/invocations`?

```
$ docker run -p 9000:8080 -it docker-handler-html-to-pdf-lambda index.handler
07 Nov 2023 09:44:45,408 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/function, handler=)
07 Nov 2023 09:44:50,473 [INFO] (rapid) extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory
START RequestId: 47197920-38e9-4c66-b8f7-780eda4200db Version: $LATEST
07 Nov 2023 09:44:50,473 [INFO] (rapid) Configuring and starting Operator Domain
07 Nov 2023 09:44:50,473 [INFO] (rapid) Starting runtime domain
07 Nov 2023 09:44:50,473 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
07 Nov 2023 09:44:50,473 [INFO] (rapid) Starting runtime without AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN , Expected?: false
2023-11-07T09:44:50.542Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'index'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start (file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}
07 Nov 2023 09:44:50,555 [WARNING] (rapid) First fatal error stored in appctx: Runtime.ExitError
07 Nov 2023 09:44:50,555 [WARNING] (rapid) Process runtime-1 exited: exit status 129
07 Nov 2023 09:44:50,555 [ERROR] (rapid) Init failed InvokeID= error=Runtime exited with error: exit status 129
07 Nov 2023 09:44:50,555 [INFO] (rapid) Starting runtime domain
07 Nov 2023 09:44:50,555 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
END RequestId: 4a08940e-4662-4700-a4b5-6f1c85498500
REPORT RequestId: 4a08940e-4662-4700-a4b5-6f1c85498500  Init Duration: 0.14 ms  Duration: 82.04 ms      Billed Duration: 83 ms  Memory Size: 3008 MB    Max Memory Used: 3008 MB
^C07 Nov 2023 09:47:54,840 [INFO] (rapid) Received signal signal=interrupt
07 Nov 2023 09:47:54,840 [INFO] (rapid) Shutting down...
07 Nov 2023 09:47:54,841 [WARNING] (rapid) Reset initiated: SandboxTerminated
07 Nov 2023 09:47:54,841 [INFO] (rapid) Stopping runtime domain
07 Nov 2023 09:47:54,841 [INFO] (rapid) Waiting for runtime domain processes termination
07 Nov 2023 09:47:54,841 [INFO] (rapid) Stopping operator domain
07 Nov 2023 09:47:54,841 [INFO] (rapid) Starting runtime domain
```

**Comment by tonysamperi** [comment]
Same here bro

**Comment by ghost** [comment]
@SinBirb any luck?

**Comment by bmitmanski** [comment]
In my case I had `ImportModuleError` on newest Docker. Reverted Docker engine to v20 and it works.

**Comment by ghost** [comment]
In my case I was missing a Lambda-defined environment variable. `${LAMBDA_TASK_ROOT}`
```
COPY index.js ${LAMBDA_TASK_ROOT}
```
Here is the official documentation.
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-image.html

**Comment by godcrampy** [comment]
Closing. The latest version of RICs across all supported Node runtimes (18 / 20 / 22) support [ESM modules](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/).
