### ISSUE TITLE
OpenSSL broken in nodejs20

### ISSUE THREAD

**Issue by elieux** [aws/aws-lambda-base-images#137]
Hi, it seems OpenSSL is pretty broken in the latest amazon/aws-lambda-nodejs:20.

```
> docker inspect -f "{{.RepoDigests}}" amazon/aws-lambda-nodejs:20
[amazon/aws-lambda-nodejs@sha256:88293c675526b4c62ccec74e3c30458932fc42e6a282f798aae461630b5f448e]
```

## Testcase: openssl

```
> docker run --rm -it --entrypoint /bin/sh amazon/aws-lambda-nodejs:20
sh-5.2# openssl
sh: openssl: command not found
sh-5.2# dnf install -y openssl
[...]
Installing: openssl;1:3.0.8-1.amzn2023.0.9;x86_64;amazonlinux
Complete.
sh-5.2# openssl version
openssl: symbol lookup error: openssl: undefined symbol: SSL_get_srp_g, version OPENSSL_3.0.0
```

## Testcase: python

```
sh-5.2# dnf install -y python
[...]
Installing: python3-setuptools-wheel;59.6.0-2.amzn2023.0.4;noarch;amazonlinux
Installing: whois-nls;5.5.10-1.amzn2023.0.2;noarch;amazonlinux
Installing: mkpasswd;5.5.10-1.amzn2023.0.2;x86_64;amazonlinux
Installing: libxcrypt;4.4.33-7.amzn2023;x86_64;amazonlinux
Installing: libxcrypt-compat;4.4.33-7.amzn2023;x86_64;amazonlinux
Installing: python3-pip-wheel;21.3.1-2.amzn2023.0.5;noarch;amazonlinux
Installing: gdbm-libs;1:1.19-2.amzn2023.0.2;x86_64;amazonlinux
Installing: expat;2.5.0-1.amzn2023.0.2;x86_64;amazonlinux
Installing: python-unversioned-command;3.9.16-1.amzn2023.0.6;noarch;amazonlinux
Installing: python3-pip;21.3.1-2.amzn2023.0.5;noarch;amazonlinux
Installing: python3-setuptools;59.6.0-2.amzn2023.0.4;noarch;amazonlinux
Installing: python3;3.9.16-1.amzn2023.0.6;x86_64;amazonlinux
Installing: python3-libs;3.9.16-1.amzn2023.0.6;x86_64;amazonlinux
Complete.
sh-5.2# python -m ssl
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.9/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /usr/lib64/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so: undefined symbol: COMP_get_type, version OPENSSL_3.0.0
```

**Comment by elieux** [comment]
It seems to have been there since the first published release:

 ```
 > docker run --rm -it --entrypoint /bin/sh amazon/aws-lambda-nodejs:20.2023.11.10.13 -c "dnf install -y openssl && openssl"
[...]
Installing: openssl;1:3.0.8-1.amzn2023.0.8;x86_64;amazonlinux
Complete.
openssl: symbol lookup error: openssl: undefined symbol: SSL_get_srp_g, version OPENSSL_3.0.0
 ```

**Comment by elieux** [comment]
It seems this is a conflict between the system OpenSSL libraries and the ones provided for Node.js.

```
> docker run --rm -it --entrypoint /bin/sh amazon/aws-lambda-nodejs:20 -c "mv /var/lang{,x} && dnf install -y openssl && openssl version"
[...]
Installing: openssl;1:3.0.8-1.amzn2023.0.9;x86_64;amazonlinux
Complete.
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

**Comment by smirnoal** [comment]
nodejs20 is using different openssl version, not the one installed with the OS.

You can override `LD_LIBRARY_PATH` env variable if you need to execute `openssl` or `python` binaries
```
% docker run -it --rm --entrypoint bash amazon/aws-lambda-nodejs:20
# dnf install -y openssl
# LD_LIBRARY_PATH="" openssl
help:

Standard commands
asn1parse         ca                ciphers           cmp               
cms               crl               crl2pkcs7         dgst              
dhparam           dsa               dsaparam          ec                
ecparam           enc               engine            errstr   
...
# dnf install -y python
# LD_LIBRARY_PATH="" python -m ssl
# 
```

**Comment by elieux** [comment]
Yeah, it's not ideal, to say the least. If there is no other resolution planned for this, the ticket can be closed.

I'll see if I can work around it like you suggested.
