### ISSUE TITLE
Concurrent request ends up in runtime memory error

### ISSUE THREAD

**Issue by karthikpdc** [aws/aws-lambda-base-images#145]
If i run any base image in docker it crashes when a concurrent request is made. In AWS environment it will create new instance to handle the request but here there will be only one instance so it will not handle the other request but it should return graceful error instead of runtime error and crashing the container.

Steps to reproduce. Just follow these [steps](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-image.html) to create a basic image and run it in docker container. 

Make concurrent request to invoke your function then the container will crash with below runtime error.
`(rapid) ReserveFailed: AlreadyReserved
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6af115]
goroutine 62 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
        /LambdaRuntimeLocal/lambda/rapidcore/server.go:666 +0xf5
created by go.amzn.com/lambda/rapidcore.(*Server).Invoke
        /LambdaRuntimeLocal/lambda/rapidcore/server.go:649 +0x23d`

**Comment by jmehnle** [comment]
This is really https://github.com/aws/aws-lambda-runtime-interface-emulator/issues/97.

**Comment by godcrampy** [comment]
The Lambda image is not designed to be concurrent. An execution environment handles one invoke at a time. The way lambda scales is spawning multiple [execution environments](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html). The Runtime Interface Client cannot handle multiple invokes at one time.

**Comment by jmehnle** [comment]
@godcrampy, this limitation was mostly well understood. However, it would've been good to simply not accept additional requests instead of crashing the container.
