### ISSUE TITLE
Python Version 3.12 Logging init error

### ISSUE THREAD

**Issue by werebear73-tritelph** [aws/aws-lambda-base-images#165]
I'm getting the following error.  It just recently started happening.  Does anyone have any clues?

```
Traceback (most recent call last):
  File "/app/lambda_function.py", line 1, in <module>
    import logging
  File "/app/logging/__init__.py", line 618
    raise NotImplementedError, 'emit must be implemented '\
                             ^
SyntaxError: invalid syntax
```

**Comment by leandrodamascena** [comment]
Not sure if this issue is still valid or can be closed, but looks like you're installing `logging` library (https://pypi.org/project/logging/) instead of using the one provided by cpython.

>   File "/app/logging/__init__.py", line 618
    raise NotImplementedError, 'emit must be implemented '\

I installed this library locally and I can see the line 618
![image](https://github.com/user-attachments/assets/bb8c1b77-8e14-4a25-9f5e-cc56263664f0)

Remove this library and use the one provided by the Python itself.
