### ISSUE TITLE
pip3 error subprocess command

### ISSUE THREAD

**Issue by ashraf133** [aws/aws-lambda-base-images#66]
Hello
I faced this error while executing the official example : https://docs.aws.amazon.com/lambda/latest/dg/python-image.html

> [4/4] RUN  pip3 install -r requirements.txt --target "/var/task":                                                                          

#0 10.79 ERROR: Exception:                                                                                                                    

#0 10.79 Traceback (most recent call last):                                                                                                   

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper                   

#0 10.79     status = run_func(*args)                                                                                                         

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper

#0 10.79     return func(self, options, args)

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 285, in run

#0 10.79     session = self.get_default_session(options)

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 75, in get_default_session

#0 10.79     self._session = self.enter_context(self._build_session(options))

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 89, in _build_session

#0 10.79     session = PipSession(

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_internal/network/session.py", line 282, in __init__

#0 10.79     self.headers["User-Agent"] = user_agent()

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_internal/network/session.py", line 122, in user_agent

#0 10.79     linux_distribution = distro.name(), distro.version(), distro.codename()

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_vendor/distro.py", line 341, in version

#0 10.79     return _distro.version(pretty, best)

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_vendor/distro.py", line 861, in version

#0 10.79     self.uname_attr("release"),

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_vendor/distro.py", line 1052, in uname_attr

#0 10.79     return self._uname_info.get(attribute, "")

#0 10.79   File "/var/lang/lib/python3.8/functools.py", line 967, in __get__

#0 10.79     val = self.func(instance)

#0 10.79   File "/var/lang/lib/python3.8/site-packages/pip/_vendor/distro.py", line 1186, in _uname_info

#0 10.79     stdout = subprocess.check_output(cmd, stderr=devnull)

#0 10.79   File "/var/lang/lib/python3.8/subprocess.py", line 415, in check_output

#0 10.79     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

#0 10.79   File "/var/lang/lib/python3.8/subprocess.py", line 516, in run

#0 10.79     raise CalledProcessError(retcode, process.args,

#0 10.79 subprocess.CalledProcessError: Command '('uname', '-rs')' returned non-zero exit status 1.

For your information : it works correctly few days ago ( i have tested with python3.8 and 3.9 )

**Comment by ashraf133** [comment]
i use this command to build : 
root@me:~/test# docker buildx build --platform linux/arm64 -t XXXXXXXX.dkr.ecr.eu-west-3.amazonaws.com/project:v0.0.0 . --load
